### ISSUE TITLE
Hybrid App Samples Missing

### ISSUE THREAD

**Issue by patnaikshekhar** [forcedotcom/SalesforceMobileSDK-Samples#41]
The repository mentions that there are hybrid app samples however I can't find those when I clone the repository.

**Comment by trooper2013** [comment]
@patnaikshekhar  Here are a few samples.

[SDK Samples] (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/master/hybrid/SampleApps)

[Dreamhouse Sample App] (https://github.com/dreamhouseapp/dreamhouse-mobile-app)

**Comment by bhariharan** [comment]
@patnaikshekhar This repository is deprecated. Check out our samples in our source repos here:
* [iOS](https://github.com/forcedotcom/SalesforceMobileSDK-iOS).
* [Android](https://github.com/forcedotcom/SalesforceMobileSDK-Android).

**Comment by wmathurin** [comment]
Also the HTML/JavaScript for our sample apps live here:
https://github.com/forcedotcom/SalesforceMobileSDK-Shared/tree/master/samples

If you generate an hybrid application with forceios or forcedroid, you can simply copy any of the samples into the application www/  directory by doing:
```
cp -r SalesforceMobileSDK-Shared/samples/one-of the-sample-app/*  www/
cordova prepare 
```

**Comment by patnaikshekhar** [comment]
Thanks
