### ISSUE TITLE
Where is NativeSqlAggregator

### ISSUE THREAD

**Issue by zaitsman** [forcedotcom/SalesforceMobileSDK-Samples#43]
In the readme.md it is mentioned that there should be a NativeSqlAggregator app that shows how to use SFSmartStore.

But i can't find it in the repo on all three available branches?

**Comment by wmathurin** [comment]
This repo has not been updated in five years.
NativeSqlAggregator no longer exists. 

Please checkout our [documentation](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_about.htm) and [trail](https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_offline/mobilesdk_offline_smartstore) to learn about SmartStore.
